AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    ce84ee80-4339-408e-ae8a-afbda72c4425:
      size:
        width: 400
        height: 300
      position:
        x: 154
        'y': 323
      z: 0
      embeds:
        - a53e02a2-1868-4357-9677-db0641c4ea84
        - 159515ca-99f7-458f-9a79-32e72fdc465d
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - b30ef676-f0c0-4cb6-949d-c7688a9146a8
        - 972c8533-804f-4863-9b9a-32a36d178a8e
    972c8533-804f-4863-9b9a-32a36d178a8e:
      size:
        width: 80
        height: 80
      position:
        x: 420
        'y': 350
      z: 1
      parent: ce84ee80-4339-408e-ae8a-afbda72c4425
      embeds: []
      iscontainedinside:
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
    48ed8e65-3886-47f4-8885-e15a288138d1:
      size:
        width: 60
        height: 60
      position:
        x: 40
        'y': 330
      z: 0
      embeds: []
    46d920b5-d5d1-4e5b-8981-b4f08abeb5d5:
      source:
        id: ce84ee80-4339-408e-ae8a-afbda72c4425
      target:
        id: 48ed8e65-3886-47f4-8885-e15a288138d1
      z: 0
    b30ef676-f0c0-4cb6-949d-c7688a9146a8:
      size:
        width: 80
        height: 80
      position:
        x: 420
        'y': 530
      z: 1
      parent: ce84ee80-4339-408e-ae8a-afbda72c4425
      embeds: []
      iscontainedinside:
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
    d00731d1-4662-48b1-82df-79a4d35152e4:
      size:
        width: 140
        height: 140
      position:
        x: 190
        'y': 370
      z: 1
      parent: ce84ee80-4339-408e-ae8a-afbda72c4425
      embeds:
        - 9ae53da4-51fb-44af-9155-b587d148fdb5
      iscontainedinside:
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
    9ae53da4-51fb-44af-9155-b587d148fdb5:
      size:
        width: 60
        height: 60
      position:
        x: 220
        'y': 410
      z: 2
      parent: d00731d1-4662-48b1-82df-79a4d35152e4
      embeds: []
      isassociatedwith:
        - 48ed8e65-3886-47f4-8885-e15a288138d1
      iscontainedinside:
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
        - d00731d1-4662-48b1-82df-79a4d35152e4
      dependson:
        - 46d920b5-d5d1-4e5b-8981-b4f08abeb5d5
    06584ed1-fbda-475e-9a6a-28ac173e2a94:
      source:
        id: d00731d1-4662-48b1-82df-79a4d35152e4
      target:
        id: 972c8533-804f-4863-9b9a-32a36d178a8e
      z: 1
    159515ca-99f7-458f-9a79-32e72fdc465d:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 540
      z: 1
      parent: ce84ee80-4339-408e-ae8a-afbda72c4425
      embeds: []
      iscontainedinside:
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
        - ce84ee80-4339-408e-ae8a-afbda72c4425
    a53e02a2-1868-4357-9677-db0641c4ea84:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 530
      z: 1
      parent: ce84ee80-4339-408e-ae8a-afbda72c4425
      embeds: []
Resources:
  VPCtest:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC Test
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ce84ee80-4339-408e-ae8a-afbda72c4425
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCtest
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet test
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 972c8533-804f-4863-9b9a-32a36d178a8e
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: Internet Gateway test
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 48ed8e65-3886-47f4-8885-e15a288138d1
  GatewayToInternet:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPCtest
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 46d920b5-d5d1-4e5b-8981-b4f08abeb5d5
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCtest
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Pravate Subnet test
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b30ef676-f0c0-4cb6-949d-c7688a9146a8
  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCtest
      Tags:
        - Key: Name
          Value: Route Table test
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d00731d1-4662-48b1-82df-79a4d35152e4
  RoutePublicTest:
    Type: 'AWS::EC2::Route'
    DependsOn: GatewayToInternet
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9ae53da4-51fb-44af-9155-b587d148fdb5
  PublicSubnetRouteAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 06584ed1-fbda-475e-9a6a-28ac173e2a94
  PrincipalSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: "sg_primary"
      VpcId: !Ref VPCtest
      GroupDescription: Security Group Principal
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Security Group Principal
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 159515ca-99f7-458f-9a79-32e72fdc465d
  DatabaseSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: "sg_database"
      VpcId: !Ref VPCtest
      GroupDescription: Security Group PAra la base de datos
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId:
            Ref: "PrincipalSecurityGroup"
      Tags:
        - Key: Name
          Value: Security Group Database
  EC2MasterTest:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-6869aa05
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: "0"
          SubnetId:
            Ref: PublicSubnet
          GroupSet:
          - "Ref": "PrincipalSecurityGroup"
      Tags:
        - Key: Name
          Value: Master Test
      UserData: {"Fn::Base64" : {"Fn::Join" : ["", ["#!/bin/bash -ex\n",
          "yum -y update\n",
          "yum -y install httpd php mysql php-mysql\n",
          "chkconfig httpd on\n",
          "service httpd start\n",
          "cd /var/www/html\n",
          "wget https://s3-us-west-2.amazonaws.com/us-west-2-aws-training/awsu-spl/spl-13/scripts/app.tgz\n",
          "tar xvfz app.tgz\n",
          "chown apache:root /var/www/html/rds.conf.php"]]}}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a53e02a2-1868-4357-9677-db0641c4ea84
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: EC2MasterTest
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      'Fn::GetAtt':
        - EC2MasterTest
        - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      'Fn::GetAtt':
        - EC2MasterTest
        - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      'Fn::GetAtt':
        - EC2MasterTest
        - PublicIp